### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by duckness** [elarkham/VGMdb-BeetsPlug#5]
https://github.com/elarkham/VGMdb-BeetsPlug/blob/2e0b763b782b43185fead92cad4a2267f25e2785/vgmdb.py#L99

this line seems to be the only line thats preventing python 3 support. Would doing something like the following snippet resolve this?
```python
def decod(self, val, codec='utf8'):
    """Ensure that all string are coded to Unicode.
    """
    # Python 2
    try:
        if isinstance(val, basestring):
            return val.decode(codec, 'ignore')
    # Python 3
    except NameError:
        if isinstance(val, str):
            return val
```

**Comment by duckness** [comment]
Ok, after taking another look, there was a bit more changes that were needed. I tried to mantain existing stuff so it remains fully backwards compatible.

https://github.com/duckness/VGMdBeets/commit/e71554e54cd581d352880bc25b7b62a928c716ea

**Comment by elarkham** [comment]
This looks good but ultimately the only reason this isn't python3 is because I haven't used beets in years. I tossed this plugin together in like a day so honestly if I ever start working on it again I'll probably just rewrite most of it (I kinda want to make it more configurable). I'm not really interested in making this backwards compatible either.

**Comment by Unknow0059** [comment]
@elarkham what do you use instead of beets?
